library(usethis)

cytokines = read.csv("../tests/testthat/testdata/Cytokines.csv", header=TRUE, row.names=NULL, check.names=FALSE, fileEncoding="UTF-8-BOM")
usethis::use_data(cytokines)
pathology = read.csv("../tests/testthat/testdata/Pathology.csv", header=TRUE, row.names=NULL, check.names=FALSE, fileEncoding="UTF-8-BOM")
usethis::use_data(pathology)
lipoproteins = read.csv("../tests/testthat/testdata/Lipoproteins.csv", header=TRUE, row.names=NULL, check.names=FALSE, fileEncoding="UTF-8-BOM")
usethis::use_data(lipoproteins)
smallmolecules = read.csv("../tests/testthat/testdata/SmallMolecules.csv", header=TRUE, row.names=NULL, check.names=FALSE, fileEncoding="UTF-8-BOM")
usethis::use_data(smallmolecules)
